name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - safe-dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Determine Image tags
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG=dev-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Frontend/Dockerfile
          push: false
          tags: unstableme02/idc-frontend:${{ steps.vars.outputs.TAG }}
          cache-from: type=gha        #uses cache from previous builds to speed up like no reinstall requirements if no change at all
          cache-to: type=gha,mode=max #stores updated for future builds


      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Backend/Dockerfile
          push: false
          tags: unstableme02/idc-backend:${{ steps.vars.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 


      - name: Push Frontend Image
        run: |
          docker push unstableme02/idc-frontend:${{ steps.vars.outputs.TAG }}

      - name: Push Backend Image
        run: |
          docker push unstableme02/idc-backend:${{ steps.vars.outputs.TAG }}

      - name: Trigger Frontend Deploy on Render
        if: ${{steps.vars.outputs.TAG == 'latest'}}
        run: |
          curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}"

      - name: Trigger Backend Deploy on Render
        if: ${{steps.vars.outputs.TAG == 'latest'}}
        run: |
          curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}"


